name: Postman API Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Install newman
        run: npm install -g newman
        
      - name: Install newman reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: newman run Serverest-API.postman_collection.json -e Serverest.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/index.html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: testResults

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Test Report - {{ secrets.REPORT_PAGE }}
          publish_branch: gh-pages
          publish_dir: testResults
          keep_files: true

      - name: Slack notification
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          status: ${{ job.status }}
        env:
          REPORT_PAGE: ${{ secrets.REPORT_PAGE }}
